default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: Q1p2m3g4
  host: localhost
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
development:
  <<: *default
  database: kh_reddit_development
test:
  <<: *default
  database: kh_reddit_test
production:
  primary: &primary_production
    <<: *default
    database: kh_reddit_production
    username: kh_reddit
    password: <%= ENV["KH_REDDIT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: kh_reddit_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: kh_reddit_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: kh_reddit_production_cable
    migrations_paths: db/cable_migrate
